name: Build and test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  check-code-formatting:
    runs-on: ubuntu-latest
    name: Check code formatting against editorconfig

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dotnet-format tool
      run: dotnet tool install -g dotnet-format
    
    - name: Check Code Format
      run: dotnet-format --check

  build-and-test:

    runs-on: ubuntu-latest
    name: dotnet build and test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Unit Test
      run: dotnet test test/FlakyTest.XUnit.Tests.Unit/FlakyTest.XUnit.Tests.Unit.csproj -c Release --no-build --verbosity normal

    - name: Integration Test
      run: dotnet test test/FlakyTest.XUnit.Tests.Integration/FlakyTest.XUnit.Tests.Integration.csproj -c Release --no-build --verbosity normal
